// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zepxkgbgpffykspbfmgu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplcHhrZ2JncGZmeWtzcGJmbWd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDMwNzYsImV4cCI6MjA2NDM3OTA3Nn0.2v4xb3-SAi3vIMINob6vtsT-41kNKqpvOL7Mm1xkUsM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);